//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SFeed.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SocialFeedEntities : DbContext
    {
        public SocialFeedEntities()
            : base("name=SocialFeedEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<UserFollower> UserFollower { get; set; }
        public virtual DbSet<WallEntry> WallEntry { get; set; }
        public virtual DbSet<UserWallEntry> UserWallEntry { get; set; }
        public virtual DbSet<WallEntryType> WallEntryType { get; set; }
    }
}
