//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SFeed.SqlRepository
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class SocialFeedEntities : DbContext
    {
        public SocialFeedEntities()
            : base("name=SocialFeedEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<GroupFollower> GroupFollower { get; set; }
        public virtual DbSet<GroupWall> GroupWall { get; set; }
        public virtual DbSet<UserComment> UserComment { get; set; }
        public virtual DbSet<UserCommentLike> UserCommentLike { get; set; }
        public virtual DbSet<UserFollower> UserFollower { get; set; }
        public virtual DbSet<UserWall> UserWall { get; set; }
        public virtual DbSet<WallPost> WallPost { get; set; }
        public virtual DbSet<WallPostLike> WallPostLike { get; set; }
        public virtual DbSet<WallPostType> WallPostType { get; set; }
    
        public virtual ObjectResult<GetWallPost_Result> GetWallPost(string postId)
        {
            var postIdParameter = postId != null ?
                new ObjectParameter("PostId", postId) :
                new ObjectParameter("PostId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetWallPost_Result>("GetWallPost", postIdParameter);
        }
    
        public virtual ObjectResult<GetLatestComments_Result> GetLatestComments(string postId)
        {
            var postIdParameter = postId != null ?
                new ObjectParameter("PostId", postId) :
                new ObjectParameter("PostId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetLatestComments_Result>("GetLatestComments", postIdParameter);
        }
    }
}
