//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SFeed.SqlRepository
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class SocialFeedEntities : DbContext
    {
        public SocialFeedEntities()
            : base("name=SocialFeedEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<GroupFollower> GroupFollower { get; set; }
        public virtual DbSet<GroupWall> GroupWall { get; set; }
        public virtual DbSet<UserComment> UserComment { get; set; }
        public virtual DbSet<UserCommentLike> UserCommentLike { get; set; }
        public virtual DbSet<UserFollower> UserFollower { get; set; }
        public virtual DbSet<UserWall> UserWall { get; set; }
        public virtual DbSet<WallPost> WallPost { get; set; }
        public virtual DbSet<WallPostLike> WallPostLike { get; set; }
        public virtual DbSet<WallPostType> WallPostType { get; set; }
    
        public virtual ObjectResult<GetLatestComments_Result> GetLatestComments(string postId)
        {
            var postIdParameter = postId != null ?
                new ObjectParameter("PostId", postId) :
                new ObjectParameter("PostId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetLatestComments_Result>("GetLatestComments", postIdParameter);
        }
    
        public virtual ObjectResult<GetWallPost_Result> GetWallPost(string postId)
        {
            var postIdParameter = postId != null ?
                new ObjectParameter("PostId", postId) :
                new ObjectParameter("PostId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetWallPost_Result>("GetWallPost", postIdParameter);
        }
    
        public virtual ObjectResult<GetWall_Result> GetUserWall(string userId, Nullable<System.DateTime> olderThan, Nullable<int> size)
        {
            var userIdParameter = userId != null ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(string));
    
            var olderThanParameter = olderThan.HasValue ?
                new ObjectParameter("OlderThan", olderThan) :
                new ObjectParameter("OlderThan", typeof(System.DateTime));
    
            var sizeParameter = size.HasValue ?
                new ObjectParameter("Size", size) :
                new ObjectParameter("Size", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetWall_Result>("GetUserWall", userIdParameter, olderThanParameter, sizeParameter);
        }
    
        public virtual ObjectResult<GetWall_Result> GetGroupWall(string groupId, Nullable<System.DateTime> olderThan, Nullable<int> size)
        {
            var groupIdParameter = groupId != null ?
                new ObjectParameter("GroupId", groupId) :
                new ObjectParameter("GroupId", typeof(string));
    
            var olderThanParameter = olderThan.HasValue ?
                new ObjectParameter("OlderThan", olderThan) :
                new ObjectParameter("OlderThan", typeof(System.DateTime));
    
            var sizeParameter = size.HasValue ?
                new ObjectParameter("Size", size) :
                new ObjectParameter("Size", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetWall_Result>("GetGroupWall", groupIdParameter, olderThanParameter, sizeParameter);
        }
    }
}
