//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SFeed.SqlRepository
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserCommentLike
    {
        public long CommentId { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
    
        public virtual UserComment UserComment { get; set; }
        public virtual UserCommentLike UserCommentLike1 { get; set; }
        public virtual UserCommentLike UserCommentLike2 { get; set; }
    }
}
